# Generated by Django 3.2.3 on 2021-07-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idRutCli', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número Rut del cliente')),
                ('dvRun', models.CharField(max_length=1, verbose_name='Dígito Verificador')),
                ('nombreCli', models.CharField(max_length=70, verbose_name='Nombre Cliente')),
                ('apellidocli', models.CharField(max_length=80, verbose_name='Apellido Cliente')),
            ],
        ),
    ]
