# Generated by Django 3.2.3 on 2021-07-11 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscrito',
            fields=[
                ('idSuscripcion', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador de la Suscripción')),
                ('nombreUser', models.CharField(help_text='Introduzca el nombre de usuario', max_length=30, unique=True, verbose_name='Nombre de usuario')),
                ('fechaSuscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha en la que el usuario se suscribió')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador del Usuario')),
                ('nombreUser', models.CharField(help_text='Introduzca el nombre de usuario', max_length=30, unique=True, verbose_name='Nombre de usuario')),
                ('passwordUser', models.CharField(help_text='Introduzca la contraseña', max_length=10, verbose_name='Contraseña')),
                ('idRutCli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Número Rut sin dígito verificador')),
            ],
        ),
    ]
